name: robot-web-test

on:
  push:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
      - name: Run test
        run: |
          docker run --shm-size=1g -e BROWSER=headlesschrome \
          -v ${{github.workspace}}/test:/opt/robotframework/tests:Z \
          -v ${{github.workspace}}/report:/opt/robotframework/reports:Z \
          -v ${{github.workspace}}/steps:/opt/robotframework/steps:Z \
          -v ${{github.workspace}}/template:/opt/robotframework/template:Z \
          --user 1001:1000 \
          ppodgorsek/robot-framework:latest