name: robot-web-test

on:
  push:
    branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Create folder for reports
          run: mkdir reports
        - name: Run test
          run: |
            docker run --shm-size=1g -e BROWSER=headlesschrome \
            -v ${{github.workspace}}/test:/opt/robotframework/tests:Z \
            -v ${{github.workspace}}/report:/opt/robotframework/reports:Z \
            -v ${{github.workspace}}/steps:/opt/robotframework/steps:Z \
            --user 1001:1000 \
            ppodgorsek/robot-framework:latest
        
        - name: Upload reports
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
          # set path to Robot Framework results reports. Exclude dummy file that is needed because of ppodgorsek image privileges.
            path: ${{ github.workspace }}/reports
          # repository name is needed for posting test report in the next step
