name: robot-web-test

on:
  push:
    branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Create folder for reports
          run: mkdir reports
        - name: test
          run: |
            docker run --shm-size=1g -e BROWSER=headlesschrome \
            -v ${{github.workspace}}/test:/opt/robotframework/tests:Z \
            -v ${{github.workspace}}/report:/opt/robotframework/reports:Z \
            --user 1001:1000 \
            ppodgorsek/robot-framework:latest
