name: robot-web-test

on:
  push:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
      - uses: actions/checkout@v3
      - name: Create folder for reports
        run: mkdir reports
      
      - name: Run test
        run: |
          docker run --shm-size=1g -e BROWSER=headlesschrome \
          -v ${{github.workspace}}/test:/opt/robotframework/tests:Z \
          -v ${{github.workspace}}/report:/opt/robotframework/reports:Z \
          -v ${{github.workspace}}/steps:/opt/robotframework/steps:Z \
          -v ${{github.workspace}}/template:/opt/robotframework/templates:Z \
          --user 1001:1000 \
          ppodgorsek/robot-framework:latest
  
      - name: Publish test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          path: reports